# Generated by Django 4.2.13 on 2024-07-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('noted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('combat_level', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('high_alch', models.CharField(default='value', max_length=50)),
                ('npcs', models.ManyToManyField(through='scape07db.Drop', to='scape07db.npc')),
            ],
        ),
        migrations.AddField(
            model_name='drop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scape07db.item'),
        ),
        migrations.AddField(
            model_name='drop',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scape07db.npc'),
        ),
    ]
